# Site settings
title: 37 woof
description: "commentary from an interesting perspective"
twitter_username: 37dogs
url: "http://127.0.0.1:4000"
author:
  name: "Brandon Fannin"
  email: "brandon@37dogs.com"
  url: "http://www.37dogs.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# Custom variables
version: "1.1.0"

# Options
reverse: true

# Gems
gems: ['jekyll-lunr-js-search']

#Lunr search excludes
lunr_search:
  excludes: [rss.xml, atom.xml]
